name: setup-rclone
description: setup Rclone on GitHub Runner in Ubuntu
inputs:
  rclone_config:
    description: Rclone config file encoded in base64
    required: true
    default: false

runs:
  using: composite
  steps:
    - name: Check platform
      shell: bash
      run: if [[ "${{ runner.os }}" != "Linux" ]]; then echo "::error::Unsupported platform - ${{ runner.os }}"; exit 1; fi
    - name: Download Rclone
      shell: bash
      working-directory: ${{ runner.temp }}
      run: |
        version=$(curl -s $GITHUB_API_URL/repos/rclone/rclone/releases/latest | jq -r .tag_name)
        echo ::group::Downloading Rclone $version
        aria2c -x 16 $GITHUB_SERVER_URL/rclone/rclone/releases/download/$version/rclone-$version-linux-amd64.zip
        7z e rclone-$version-linux-amd64.zip rclone -oRclone -r
        rm rclone-$version-linux-amd64.zip
        echo ::endgroup::
    - name: Install Rclone on tool cache
      uses: heinokesoe/actions@tool-cache
      with:
        folder_name: Rclone
    - name: Sign in to Rclone using Rclone config
      shell: bash
      if: inputs.rclone_config != 'false'
      run: |
        echo ::group::Signing in to Rclone using Rclone config
        mkdir ~/.config/rclone/
        echo $rclone_config | base64 -d > ~/.config/rclone/rclone.conf
        echo ::endgroup::
      env:
        rclone_config: ${{ inputs.rclone_config }}
