name: Tool Cache
description: Implementation of Tool Cache in composite GitHub Actions
inputs:
  folder_name:
    description: Folder name of the software inside runner temp
    required: true
    default: false
    
runs:
  using: composite
  steps:
    - name: Check platform
      shell: bash
      run: if [[ "${{ runner.os }}" != "Linux" ]]; then echo "::error::Unsupported platform - ${{ runner.os }}"; exit 1; fi
    - name: Install software to tool cache
      shell: bash
      if: inputs.folder_name != false
      run: |
        echo ::group::Installing $folder_name to tool cache
        mkdir -p $RUNNER_TOOL_CACHE/$folder_name/
        mv $RUNNER_TEMP/$folder_name/* $RUNNER_TOOL_CACHE/$folder_name/
        echo ::endgroup::
      env:
        folder_name: ${{ inputs.folder_name }}
    - name: Add software tool cache folder to path
      shell: bash
      run: |
        echo ::group::Adding $folder_name tool cache folder to path
        echo $RUNNER_TOOL_CACHE/$folder_name >> $GITHUB_PATH
        echo ::endgroup::
      env:
        folder_name: ${{ inputs.folder_name }}
